### ISSUE TITLE
IllegalArgumentException: Invalid character (CR or LF) found in method name

### ISSUE THREAD

**Issue by kr1zz** [fadeoutsoftware/WASDI#155]
This can be found sometimes in the log. It is not clear if it has a practical effect or not (he lines about SENTINEL might be unrelated, they're here to mark the timestamp).

```java
2019-08-13T10:34:08.011: QueryExecutor.buildResultViewModel: Search Done: found 8 results
2019-08-13T10:34:08.011: OpenSearchResource.search: found 8 results for SENTINEL
INFO: org.apache.coyote.http11.AbstractHttp11Processor: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:236)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by pcampanella** [comment]
Not our bug
